# Site settings
title: Homepage
baseurl: ""
url: https://lizn-zn.github.io/
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Zenan Li
  desc: Post-doc researcher @ ETH Zürich
  email: zenan.li@inf.ethz.ch
  selfie: images/bio-photo.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: Lizn-zn
  google_plus:
  instagram:
  keybase:
  linkedin: 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: https://math.stackexchange.com/users/602936/zenan-li
  steam:
  tumblr:
  gitlab:
  twitter: Null
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
